# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import os

os.listdir('/content')

"""**Check Book is readable or  not**"""

with open('/content/gutenberg.txt', 'r', encoding='utf-8') as f:
    raw_text = f.read()

print(raw_text[:1000])   # sanity check

"""**Clean the text Properly**"""

import re

text = raw_text.lower()

# Remove Gutenberg header/footer (robust enough)
text = re.split(r'\*\*\* start of', text, flags=re.IGNORECASE)[-1]
text = re.split(r'\*\*\* end of', text, flags=re.IGNORECASE)[0]

# Keep only letters and sentence markers
text = re.sub(r'[^a-z\.\!\?\s]', ' ', text)

# Normalize spaces
text = re.sub(r'\s+', ' ', text).strip()

"""**Tokenization**"""

words = text.split()
print("Total words:", len(words))

"""**Build the 2-gram Markov model**"""

from collections import defaultdict

markov_2 = defaultdict(list)

for i in range(len(words) - 2):
    key = (words[i], words[i+1])
    markov_2[key].append(words[i+2])

print("2-gram states:", len(markov_2))

"""**Generate text from 2-gram model**"""

import random

def generate_2gram(chain, length=200):
    w1, w2 = random.choice(list(chain.keys()))
    output = [w1, w2]

    for _ in range(length):
        candidates = chain.get((w1, w2))
        if not candidates:
            break
        w3 = random.choice(candidates)
        output.append(w3)
        w1, w2 = w2, w3

    return " ".join(output)

print(generate_2gram(markov_2))

"""**Build a 3-gram Morkov model**"""

from collections import defaultdict

markov_3 = defaultdict(list)

for i in range(len(words) - 3):
    key = tuple(words[i:i+3])
    markov_3[key].append(words[i+3])

print("3-gram states:", len(markov_3))

"""**Generate Text From 3-gram Model**"""

import random

def generate_3gram(chain, length=200):
    w = list(random.choice(list(chain.keys())))
    output = w.copy()

    for _ in range(length):
        key = tuple(w[-3:])
        candidates = chain.get(key)
        if not candidates:
            break
        next_word = random.choice(candidates)
        output.append(next_word)
        w.append(next_word)

    return " ".join(output)

print(generate_3gram(markov_3))